
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: DairySense2025
  host: 127.0.0.1
  port: 5432
  pool: 5

development:
  <<: *default
  database: Dados

test:
  <<: *default
  database: backend_dairy_sense_test

production:
  primary: &primary_production
    <<: *default
    database: Dados
    username: postgres
    password: <%= ENV['DairySense2025'] %>
  cache:
    <<: *primary_production
    database: backend_dairy_sense_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_dairy_sense_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_dairy_sense_production_cable
    migrations_paths: db/cable_migrate
