cio_detection:
  cron: "*/10 * * * *"     # a cada 10 min
  class: "CioDetectionJob"
  queue: detectors
  args:
    since_minutes: 2880 #2 dias
    sustain_minutes: 30 #tempo de pico mínimo para considerar cio
    window_minutes: 10
    z_threshold: 2.5
